"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { DashboardShell } from "../../../components/DashboardShell";
import { Category, createComplaint } from "../../../lib/api";
import { getCategories } from "../../../lib/api";
export default function NewComplaintPage() {
  const router = useRouter();
  const [categories, setCategories] = useState<Category[]>([]);
  const [form, setForm] = useState({ customer_name: "", customer_contact: "", subject: "", description: "", category_id: "", priority: "MEDIUM", expected_resolution_date: "" });
  const [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { getCategories().then(setCategories).catch((reason) => setError(reason.message)); }, []);
  const change = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await createComplaint({ ...form, category_id: Number(form.category_id) }); router.push("/complaints"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create complaint."); setSaving(false); } }
  const input = (key: keyof typeof form, label: string, type = "text") => <label className="block text-sm font-semibold text-ink">{label}<input required type={type} value={form[key]} onChange={(e) => change(key, e.target.value)} className="field mt-2 w-full px-3.5 py-3 text-sm" /></label>;
  return <DashboardShell><div className="mx-auto max-w-4xl"><Link href="/complaints" className="text-sm font-bold text-brand hover:text-blue-700">← Back to complaints</Link><div className="mt-5 mb-8"><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-brand">New record</p><h2 className="text-3xl font-bold tracking-tight text-ink">Create a complaint</h2><p className="mt-2 text-sm leading-6 text-muted">Capture the customer issue clearly. New complaints enter the queue as unassigned.</p></div><form onSubmit={submit} className="surface overflow-hidden">{error && <p className="m-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="border-b border-slate-100 px-5 py-5 sm:px-8"><h3 className="font-bold text-ink">Customer and issue</h3><p className="mt-1 text-sm text-muted">Who is contacting you and what do they need help with?</p></div><div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-8">{input("customer_name", "Customer name")}{input("customer_contact", "Customer contact")}{input("subject", "Subject")}<label className="block text-sm font-semibold text-ink">Expected resolution date<input required type="date" value={form.expected_resolution_date} onChange={(e) => change("expected_resolution_date", e.target.value)} className="field mt-2 w-full px-3.5 py-3 text-sm" /></label><label className="block text-sm font-semibold text-ink">Category<select required value={form.category_id} onChange={(e) => change("category_id", e.target.value)} className="field mt-2 w-full px-3.5 py-3 text-sm"><option value="">Select a category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block text-sm font-semibold text-ink">Priority<select value={form.priority} onChange={(e) => change("priority", e.target.value)} className="field mt-2 w-full px-3.5 py-3 text-sm">{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((v) => <option key={v}>{v}</option>)}</select></label><label className="block text-sm font-semibold text-ink sm:col-span-2">Description<textarea required minLength={1} rows={6} value={form.description} onChange={(e) => change("description", e.target.value)} placeholder="Describe the issue, context, and any relevant details…" className="field mt-2 w-full resize-y px-3.5 py-3 text-sm leading-6" /></label></div><div className="flex flex-col-reverse gap-3 border-t border-slate-100 bg-slate-50/50 p-5 sm:flex-row sm:justify-end sm:p-6"><Link href="/complaints" className="rounded-xl border border-slate-200 bg-white px-5 py-3 text-center text-sm font-bold text-muted hover:bg-slate-50">Cancel</Link><button disabled={saving} className="rounded-xl bg-brand px-5 py-3 text-sm font-bold text-white shadow-lg shadow-blue-200 hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50">{saving ? "Creating complaint…" : "Create complaint"}</button></div></form></div></DashboardShell>;
}
