"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { DashboardShell } from "../../components/DashboardShell";
import { StatusBadge } from "../../components/StatusBadge";
import { Complaint, Employee, Category, getCategories, getComplaints, getEmployees } from "../../lib/api";

const statuses = ["NEW", "ASSIGNED", "IN_PROGRESS", "RESOLVED", "CLOSED"];
const priorities = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
const isOverdue = (item: Complaint) => !["RESOLVED", "CLOSED"].includes(item.status) && new Date(`${item.expected_resolution_date}T23:59:59`) < new Date();

export default function ComplaintsPage() {
  const [items, setItems] = useState<Complaint[]>([]), [total, setTotal] = useState(0), [page, setPage] = useState(1);
  const [search, setSearch] = useState(""), [status, setStatus] = useState(""), [priority, setPriority] = useState(""), [category, setCategory] = useState(""), [employee, setEmployee] = useState("");
  const [categories, setCategories] = useState<Category[]>([]), [employees, setEmployees] = useState<Employee[]>([]), [sortBy, setSortBy] = useState("created_at"), [sortOrder, setSortOrder] = useState("desc"), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const pageSize = 10;
  useEffect(() => { Promise.all([getCategories(), getEmployees()]).then(([c, e]) => { setCategories(c); setEmployees(e); }).catch((reason) => setError(reason.message)); }, []);
  useEffect(() => { setLoading(true); getComplaints({ search, status, priority, category_id: category, employee_id: employee, sort_by: sortBy, sort_order: sortOrder, page, page_size: pageSize }).then((r) => { setItems(r.items); setTotal(r.total); setError(""); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }, [search, status, priority, category, employee, sortBy, sortOrder, page]);
  const filter = (setter: (v: string) => void, value: string) => { setter(value); setPage(1); };
  const pages = Math.max(1, Math.ceil(total / pageSize)), selectClass = "field w-full px-3 py-2.5 text-sm";
  return <DashboardShell><div className="mx-auto max-w-7xl">
    <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-brand">Workspace</p><h2 className="text-3xl font-bold tracking-tight text-ink">Complaints</h2><p className="mt-2 text-sm text-muted">Search, filter, and manage every customer issue in one place.</p></div><Link href="/complaints/new" className="inline-flex justify-center rounded-xl bg-brand px-4 py-3 text-sm font-bold text-white shadow-lg shadow-blue-200 hover:bg-blue-700">+ New complaint</Link></div>
    <section className="surface overflow-hidden">
      <div className="border-b border-slate-100 bg-slate-50/50 p-4 sm:p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input value={search} onChange={(e) => filter(setSearch, e.target.value)} placeholder="Search by ID, customer, contact, or subject" className={`${selectClass} sm:col-span-2`} /><select value={status} onChange={(e) => filter(setStatus, e.target.value)} className={selectClass}><option value="">All statuses</option>{statuses.map((v) => <option key={v}>{v.replace("_", " ")}</option>)}</select><select value={priority} onChange={(e) => filter(setPriority, e.target.value)} className={selectClass}><option value="">All priorities</option>{priorities.map((v) => <option key={v}>{v}</option>)}</select><select value={category} onChange={(e) => filter(setCategory, e.target.value)} className={selectClass}><option value="">All categories</option>{categories.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select><select value={employee} onChange={(e) => filter(setEmployee, e.target.value)} className={selectClass}><option value="">All employees</option>{employees.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select><select value={sortBy} onChange={(e) => filter(setSortBy, e.target.value)} className={selectClass}><option value="created_at">Sort: Created date</option><option value="updated_at">Sort: Updated date</option><option value="expected_resolution_date">Sort: Resolution date</option><option value="customer_name">Sort: Customer name</option><option value="priority">Sort: Priority</option><option value="status">Sort: Status</option></select><button type="button" onClick={() => filter(setSortOrder, sortOrder === "desc" ? "asc" : "desc")} className="field px-3 py-2.5 text-left text-sm font-semibold hover:bg-white">Order: {sortOrder === "desc" ? "Newest first ↓" : "Oldest first ↑"}</button></div></div>
      {error && <p className="m-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}
      <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="border-b border-slate-100 text-[10px] font-bold uppercase tracking-[.14em] text-slate-400"><tr>{["ID", "Customer", "Subject", "Priority", "Assigned employee", "Status", "Due date"].map((h) => <th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">
        {loading ? <tr><td colSpan={7} className="p-12 text-center text-sm text-muted">Loading complaints…</td></tr> : items.map((item) => <tr key={item.id} className="group hover:bg-blue-50/40"><td className="px-5 py-4"><Link href={`/complaints/${item.id}`} className="font-bold text-brand hover:underline">#{item.id}</Link></td><td className="px-5 py-4"><p className="font-semibold text-ink">{item.customer_name}</p><p className="mt-1 text-xs text-muted">{item.customer_contact}</p></td><td className="max-w-[260px] px-5 py-4"><Link href={`/complaints/${item.id}`} className="block truncate font-semibold text-ink group-hover:text-brand">{item.subject}</Link></td><td className="px-5 py-4 text-xs font-bold text-slate-600">{item.priority}</td><td className="px-5 py-4 text-muted">{employees.find((e) => e.id === item.assigned_employee_id)?.name ?? "Unassigned"}</td><td className="px-5 py-4"><StatusBadge value={item.status} /></td><td className={`px-5 py-4 text-xs font-semibold ${isOverdue(item) ? "text-red-600" : "text-muted"}`}>{isOverdue(item) && "⚠ "}{new Date(item.expected_resolution_date).toLocaleDateString()}</td></tr>)}
        {!loading && !items.length && <tr><td colSpan={7} className="p-14 text-center"><p className="font-semibold text-ink">No complaints found</p><p className="mt-1 text-sm text-muted">Try adjusting your filters or search terms.</p></td></tr>}
      </tbody></table></div>
      <div className="flex flex-col gap-3 border-t border-slate-100 p-4 text-sm text-muted sm:flex-row sm:items-center sm:justify-between"><span>{loading ? "Loading…" : `${total} complaint${total === 1 ? "" : "s"} found`}</span><div className="flex items-center gap-3"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="field px-3 py-2 font-semibold disabled:opacity-40">Previous</button><span className="font-semibold">Page {page} of {pages}</span><button disabled={page >= pages} onClick={() => setPage(page + 1)} className="field px-3 py-2 font-semibold disabled:opacity-40">Next</button></div></div>
    </section>
  </div></DashboardShell>;
}
